MYSQL_ROOT_PASSWORD: "{{ lookup('amazon.aws.secretsmanager_secret',
            'expense/dev/mysql_root_password',
            region='us-east-1') }}"
#"{{ lookup('amazon.aws.aws_ssm', '/expense/dev/mysql_root_password', region='us-east-1', decrypt=True ) }}"
