$ANSIBLE_VAULT;1.1;AES256
36656264353131626538376232613334383838663031393035643434656139666233373065323561
6263666361303234626638613366616662613331376633310a396266336164666366333363366230
66653032313831386531343738366465633538633434366230346132636137383736643265643538
6338623661323765310a633833633137633031373130663938653831333936363032306331656563
38366565303463393235326439616161383364613430326664646332653737343864613164333033
3463323230373164633934303738373761386365613566313261