# - name: testing include vs import
#   ansible.builtin.debug:
#     msg: "Hi"

# - name: testing include vs import again
#   ansible.builtin.debug:
#       msg: "Hello"

# - name: Task 1
#   debug:
#     msg: "I am task 1 inside role"

# - name: Task 2
#   debug:
#     msg: "I am task 2 inside role"

# - name: Task 3
#   debug:
#     msg: "I am task 3 inside role"

- name: Always runs
  debug:
    msg: "Task 1: I always run"

- name: Runs only if install_db is true
  debug:
    msg: "Task 2: Installing DB"
  when: install_db

- name: Runs only if install_app is true
  debug:
    msg: "Task 3: Installing APP"
  when: install_app
